name: gbdmobile
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  github_auth: ^0.0.4
  path_provider: ^1.1.0
  http: ^0.12.2
  fl_chart: ^0.12.0
 

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
